version: 1.0.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: nSHsdwlZ11znfN4BIWlt7XCmKGc92cWTndvo9/a0nFuabosEDfB/DYOHipyZf1l2
  skip_symbols: true
  on:
    branch: master